version: '3'
volumes: 
   inventory-app: {}
services: 
   mysql:
      image: mysql:8
      volumes:
      - inventory-app:/home/sql/app
      restart: always
      container_name: inventar-app-mysql
      command: --default-authentication-plugin=mysql_native_password 
      environment:
         MYSQL_DATABASE: 'tfbern-inventory'
         MYSQL_USER: 'admin'
         MYSQL_PASSWORD: 'admin'
         MYSQL_ROOT_PASSWORD: 'admin'
      ports:
      - 3307:3306
      links:
      - API
      expose:
      - 3307
   api:
      build: ./API
      container_name: inventar-app-api
      volumes:
      - inventory-app:/home/node/api
      expose: 
      - 3000
      - ${API_PORT}
      environment:
      - NODE_ENV=${NODE_ENV}
      - HOST=${HOST}
      - JWT_TOKEN=${JWT_TOKEN}
      - API_PORT=${API_PORT}
      depends_on: 
      - "mysql"
      ports:
      - ${API_PORT}:${API_PORT}
      links:
      - mysql
      
   client:
      build: 
         context: ./frontend
         args: 
            API_PORT: ${API_PORT}
      container_name: inventar-app-apache
      environment:
         - NODE_ENV=${NODE_ENV}
         - HOST=${HOST}
         - JWT_TOKEN=${JWT_TOKEN}
         - API_PORT=${API_PORT}
      expose:
      - 80
      volumes:
      - inventory-app:/home/node/apache
